version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/latest/
overwrite: true
file_exists_behavior: OVERWRITE
permissions:
  - object: /var/www/html/latest/
    owner: ubuntu
    group: ubuntu
