version: 0.2

phases:
  build:
    commands:
     
      echo "Building the project"
      
     
      mkdir -p /tmp/deploy/latest/

     
      cp index.html /tmp/deploy/latest/

artifacts:
  files:
    - '/tmp/deploy/latest/index.html'
  discard-paths: yes
